name: Docker Build and Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: david  
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate timestamp tag
        id: timestamp
        run: echo "TIMESTAMP_TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      # 👇 Force lowercase on image name in case someone edits it later
      - name: Force lowercase image name
        id: imagename
        run: |
          echo "IMAGE_NAME_LOWER=$(echo '${{ env.IMAGE_NAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.DOCKERHUB_USERNAME }}/${{ steps.imagename.outputs.IMAGE_NAME_LOWER }}:latest
            ${{ env.REGISTRY }}/${{ env.DOCKERHUB_USERNAME }}/${{ steps.imagename.outputs.IMAGE_NAME_LOWER }}:${{ steps.timestamp.outputs.TIMESTAMP_TAG }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Pull and run
      #   run: |
      #     docker stop Helen || true
      #     docker rm Helen || true
      #     docker pull ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
      #     docker run -d -p 8000:80 --name Helen ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
